spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/helloworld?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: user
    password: password
  jpa:
    database: mysql
