runtime: java
env: flex

service: processor

manual_scaling:
  instances: 1

resources:
  memory_gb: 0.768

handlers:
  - url: /.*
    script: this field is required, but ignored

env_variables:
  ENVIRONMENT: "prod"
